### PR TITLE
fix: installation of separate libs

### PR DESCRIPTION
**Pull request by vulet**
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [ ] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [ ] I have read the [WRITING DOCUMENTATION](https://docs.ark.io/guidebook/contribution-guidelines/writing-documentation.html) guidelines
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by ghost** [comment]
@vulet Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@faustbrian @supaiku0 @air1one - please review this pull request in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
@vulet A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@vulet Your pull request has been merged and marked as tier 5. _It will earn you $5 USD._

**Pull request merged**
