### PR TITLE
docs(api): update API response and curl command examples

### LINKED ISSUE #430: Inconsistencies in curl command examples on Public API docs
**Current Behavior**  
There are inconsistencies in the curl command examples on the Public API docs. 

There are command examples present in the following chapters:
* Blockchain
* Blocks
* Delegates

However, command examples are missing from these chapters:
* Node
* Peers 
* Transactions 
* Votes 
* Wallets 

**Possible Solution**  
Add curl command examples to the pages where they are missing, making the Public API documention more complete and easy to go through step by step.

### LINKED ISSUE #431: Outdated, invalid and/or inconsistent API response examples on Public API docs
**Current Behavior**  
The response examples shown on the Public API docs are often outdated, invalid and/or inconsistent. Examples of these issues are:   
* Missing data 
* Obsoleted data
* Devnet data shown for Mainnet API requests
* Mixed indentation size
* `...` character not used in a consistent manner

**Possible Solution**  
* Go through each API request used in the Public API documentation, and update the responses with up-to-date and correct data. 
* Use mainnet data only. This will make more sense for the end user, since the curl command examples all lead to the mainnet API. Using mainnet data only, the user can try the example commands and see the same results (where applicable) as shown on the docs.
* Use the same indentation for all reponse examples
* Use the `...` character in a consistent manner throughout the Public API docs (eg: use after first entry of a large array)

### PR DESCRIPTION
**Pull request by Lemii**
Resolves #430 
Resolves #431

This PR contains a overhaul of all the Public API response examples, and adds curl command examples on pages where they were missing, as well as fixing some minor styling discrepancies.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [x] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your pull request doesn't follow our [contribution guidelines](https://docs.ark.io/guidebook/contribution-guidelines/). Please review and correct it.

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
