### PR TITLE
docs: fix correctness, grammar and add short piece on Ark Network top…

### PR DESCRIPTION
**Pull request by KaiserKarel**
## Proposed changes
This chapter contained quite a bit of incorrect information, fixed that and some grammar + spelling. Added a page on the Ark network, what are relay nodes etc.

- [X] Docs (documentation only changes)

### CODE REVIEW

**Comment by ghost** [comment]
@KaiserKarel Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@faustbrian @supaiku0 @air1one - please review this pull request in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
@KaiserKarel A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@KaiserKarel Your pull request has been merged but was not assigned a bounty tier. @faustbrian @supaiku0 @air1one - please assign a bounty tier to this pull request in the next few days.

**Pull request merged**
