### PR TITLE
feat: add styles to details/summary

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Adds some styles so that the `<details>` blocks can be identified as expandable more easily. This PR also adds a border-radius to the tip/danger/warning boxes.

For reference: https://docs.ark.io/guidebook/guides/desktop.html

screencapture-localhost-8080-guidebook-guides-desktop-html-2019-04-09-14_13_27

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](/guidebook/contribution-guidelines/contributing.html) documentation
- [x] I have read the [WRITING DOCUMENTATION](/guidebook/contribution-guidelines/writing-documentation.html) guidelines

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 3. _It will earn you $25 USD._

**Comment by dated** [comment]
The `esp32` and `esp8266` documentations contain nested `<detail>` blocks. This certainly isn't ideal and those pages should probably be reworked, as imho the general documentation style and structure doesn't align to well with the rest of the docs.

For reference https://docs.ark.io/tutorials/iot/boards/esp32-adafruit/

**Pull request merged**
