### PR TITLE
Fix typo on GraphQL section title

### LINKED ISSUE #273: Typo error in documentation
**Describe the bug**

This is simply a small typo I noticed while browsing the doc: graphQL misspelled as _grahpQL_.

### PR DESCRIPTION
**Pull request by slyg**
## Proposed changes
Resolves #273

This is simply a small typo I noticed while browsing the doc.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Docs (documentation only changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] I have read the [WRITING DOCUMENTATION](https://docs.ark.io/guidebook/contribution-guidelines/writing-documentation.html) guidelines
- [x] I have added necessary documentation

### CODE REVIEW

**Comment by ghost** [comment]
@slyg Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@adrian69 @faustbrian @supaiku0 - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
@slyg Your pull request doesn't follow our [contribution guidelines](https://docs.ark.io/guidebook/contribution-guidelines/). Please review and correct it.

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
@slyg A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@slyg Your pull request has been merged and marked as tier 6. _It will earn you $1 USD._

**Comment by boldninja** [comment]
@slyg Can you provide me with your ARK address for GitHub bounty? You can also contact me on ARK's Slack - https://ark.io/slack (username : boldninja) and direct message me your address there.

**Pull request merged**
