### PR TITLE
documentation assignment: priority 1 milestones

### PR DESCRIPTION
**Pull request by KaiserKarel**
## Proposed changes
Added a bunch of stuff regarding exchanges, node setup, webhooks, docker 

## Types of changes
Documentation, code examples and menu items.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [X] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)

## Checklist

- [X] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [X] I have read the [WRITING DOCUMENTATION](https://docs.ark.io/guidebook/contribution-guidelines/writing-documentation.html) guidelines
- [X] I have added necessary documentation
<!--

### CODE REVIEW

**Comment by KaiserKarel** [comment]
Chris said we'd just squash all my commits into a single one; so I didn' t bother cleaning up the git history.

**Comment by kristjank** [comment]
@KaiserKarel make sure there are no errors during `yarn dev`. Currently we have them. Please double check

**Comment by faustbrian** [comment]
Why not send a single PR for each specific topic instead of having a dozen random topics that are unrelated combined?

That we squash commits doesn't mean that we just commit 50 random topics into 1 PR and if that is what @kristjank told you that is simply wrong.

It's impossible to make any sense out of this PR, let alone after it has been squashed. The point of squashing is that we do smaller PRs that are easy to follow.

**Comment by KaiserKarel** [comment]
This PR makes more sense when looking at the contract terms, but less sense when looking at the subject matter itself. I will turn this into multiple PRs over the weekend; but leave this one up for reviewing purposes.

**Review by kristjank — APPROVED** [review]

**Comment by kristjank** [comment]
@faustbrian I agree - we will have this further on. We worked internally in this every topic that has changed, so no worries.

**Comment by faustbrian** [comment]
Glad we follow the rules we set in place :trollface:

**Pull request merged**
