### PR TITLE
Intro blockchain review

### PR DESCRIPTION
**Pull request by KaiserKarel**
This chapter contained a lot of inconsistencies and was mostly incorrect regarding blockchain. I attempted to get it up to par; and will in a later PR improve on it.

### CODE REVIEW

**Comment by ghost** [comment]
@KaiserKarel Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@adrian69 @faustbrian @supaiku0 - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
@KaiserKarel Your pull request doesn't follow our [contribution guidelines](https://docs.ark.io/guidebook/contribution-guidelines/). Please review and correct it.

**Comment by ghost** [comment]
@KaiserKarel The [ci/circleci: build](https://circleci.com/gh/ArkEcosystem/docs/1039?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [997e34e0199373c39f24705fa8c2c8202dd485fc](https://github.com/ArkEcosystem/docs/commit/997e34e0199373c39f24705fa8c2c8202dd485fc). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/docs/1039?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by ghost** [comment]
@KaiserKarel The [ci/circleci: build](https://circleci.com/gh/ArkEcosystem/docs/1039?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [997e34e0199373c39f24705fa8c2c8202dd485fc](https://github.com/ArkEcosystem/docs/commit/997e34e0199373c39f24705fa8c2c8202dd485fc). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/docs/1039?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Review by kristjank — APPROVED** [review]

**Comment by ghost** [comment]
@KaiserKarel A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@KaiserKarel Your pull request has been merged but was not assigned a bounty tier. @adrian69 @faustbrian @supaiku0 - please assign a bounty tier to this pull request in the next few days.

**Pull request merged**
