### PR TITLE
[DO NOT MERGE] docs: update the javascript client examples

### PR DESCRIPTION
**Pull request by Pedro-Souza**
## Proposed changes
update exemple client javascript
## Types of changes

- [x] Docs (documentation only changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] I have read the [WRITING DOCUMENTATION](https://docs.ark.io/guidebook/contribution-guidelines/writing-documentation.html) guidelines

### CODE REVIEW

**Comment by faustbrian** [comment]
@Pedro-Souza conflicts

**Comment by Pedro-Souza** [comment]
@faustbrian Done.

**Comment by kristjank** [comment]
can we try to resolve one last-time. @Pedro-Souza Thanks

**Comment by faustbrian** [comment]
Those can't be merged yet as those changes are still on develop if I remember right.

**Comment by j-a-m-l** [comment]
Yes, those changes are on `develop` only.

**Comment by ghost** [comment]
Your pull request has been closed, thank you for trying to solve an issue. If you think it was closed prematurely please provide additional information.

**Pull request closed without merging**
