### PR TITLE
feat: add @dated/markdown-title-case

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

This PR adds a [package](https://github.com/dated/markdown-title-case) to discover and fix non-title-cased titles and captions by calling `yarn titles` or `yarn titles:fix`.

Example output:

```
> yarn titles
 ›   Warning: Found 1 issues in docs/api/public/troubleshooting.md

     this line : Why Am I Not Seeing All my Results?
     should be : Why Am I Not Seeing All My Results?

 ›   Warning: Found 2 issues in docs/faq/desktop-wallet.md

     this line : Why Is There a Line Through a Cloud Next to my Address?
     should be : Why Is There a Line Through a Cloud Next to My Address?

     this line : When I Open my ARK Desktop Wallet I See an Empty ARK Address Which Should Have ARK Tokens in It.
     should be : When I Open My ARK Desktop Wallet I See an Empty ARK Address Which Should Have ARK Tokens in It.

 ›   Warning: Found 2 issues in docs/faq/passphrases.md

     this line : I Lost / Deleted my 2nd Passphrase Can I Still Use my ARK Account?
     should be : I Lost / Deleted My 2nd Passphrase Can I Still Use My ARK Account?

     this line : I Lost my Passphrase. Can You Guys Reset It or Reverse my Transaction?
     should be : I Lost My Passphrase. Can You Guys Reset It or Reverse My Transaction?

 ›   Warning: Found 4 issues in docs/faq/voting-delegates.md

     this line : Is Voting a Risk for my Wallet?
     should be : Is Voting a Risk for My Wallet?

     this line : How Can I Change my Vote?
     should be : How Can I Change My Vote?

     this line : Do I Have to Re-Vote When I Receive Additional ARK Tokens in my Wallet?
     should be : Do I Have to Re-Vote When I Receive Additional ARK Tokens in My Wallet?

     this line : Do I Need to Keep my Wallet Open After I Vote?
     should be : Do I Need to Keep My Wallet Open After I Vote?

 ›   Warning: Found 9 issues
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](/guidebook/contribution-guidelines/contributing.html) documentation
- [x] I have read the [WRITING DOCUMENTATION](/guidebook/contribution-guidelines/writing-documentation.html) guidelines

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
So I don't have to fix every article @boldninja writes :trollface:

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 5. _It will earn you $5 USD._

**Comment by dated** [comment]
Just out of curiosity: if i added the feature in the docs repository directly as opposed to it's own package, the tier would have been higher?

**Comment by faustbrian** [comment]
Maybe, this PR simply added a third-party package and registered a new npm script so there isn't a reason to value it like it was specifically build just for our docs.

**Pull request merged**
