### PR TITLE
Sanitation of Explorer Guide

### PR DESCRIPTION
**Pull request by tpscrpt**
made a branch which got messed up with the recent refactor, if you'd like more detailed commits you can find it there: https://github.com/JeremiGendron/docs/commits/fix/explorer/editing/docs/cookbook/usage-guides/how-to-use-ark-explorer.md

Otherwise, this is:
- Remove double spacing except for list items
- Separate the last paragraph into Mobile/Desktop differences & Conclusion
- A few spelling/grammatical misshaps

I hope this PR is welcomed!

### CODE REVIEW

**Comment by kristjank** [comment]
can you please resolve the conflicts @JeremiGendron 
@mvega3 can you also check this content and if all green merge

**Comment by tpscrpt** [comment]
Yes

**Review by tpscrpt — COMMENTED** [review]
found a new button!

**Review by mariowhowrites — APPROVED** [review]
All looks good to me.

**Pull request merged**
