### PR TITLE
docs: create releases chapter and move migration logic there -- thus …

### PR DESCRIPTION
**Pull request by KaiserKarel**
Created a chapter with descriptions on releases, including changelogs, summaries and migration support, and removed bridgechains chapter since now it wouldn't contain anything.

### CODE REVIEW

**Comment by ghost** [comment]
@KaiserKarel Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@air1one @faustbrian @supaiku0 - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
@KaiserKarel A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@KaiserKarel Your pull request has been merged but was not assigned a bounty tier. @air1one @faustbrian @supaiku0 - please assign a bounty tier to this pull request in the next few days.

**Pull request merged**
